### ISSUE TITLE
Issue in calling the scanFile method

### ISSUE THREAD

**Issue by ravindranpandu** [begrossi/MediaScannerPlugin#1]
Hi @begrossi ,

in the Usage docs its mentioned as to Call the `cordova.plugins.MediaScannerPlugin(fileUri, successCallback, errorCallback)` instead it has to be Called as  `cordova.plugins.MediaScannerPlugin.scanFile(fileUri, successCallback, errorCallback)`

Thanks

**Comment by rodrigograca31** [comment]
@ravindranpandu I also noticed that... I will send him a pull request....

**Comment by begrossi** [comment]
Thank you, guys.
